### ISSUE TITLE
Auto-shutdown Configuration on VM

### ISSUE THREAD

**Issue by retheshnair** [terraform-providers/terraform-provider-azure#36]
Hi there,

### Terraform Version
0.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
-VM

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### ARM Configuration Files
```
{
"apiVersion": "[providers('Microsoft.DevTestLab','labs').apiVersions[0]]",
"type": "microsoft.devtestlab/schedules",
"name": "[concat('shutdown-computevm-',parameters('vmName'),copyIndex(parameters('numerationOfVMs')))]",
"location": "[resourceGroup().location]",
"dependsOn": [
"[concat('Microsoft.Compute/virtualMachines/',concat(parameters('vmName'),copyIndex(parameters('numerationOfVMs'))))]"
],
"properties": {
"status": "Enabled",
"taskType": "ComputeVmShutdownTask",
"dailyRecurrence": {
"time": "1900"
},
"timeZoneId": "W. Europe Standard Time",
"notificationSettings": {
"status": "Disabled",
"timeInMinutes": 15
},
"targetResourceId": "[resourceId('Microsoft.Compute/virtualMachines',concat(parameters('vmName'),copyIndex(parameters('numerationOfVMs'))))]"
}
}
```
.

### Expected Behavior
Auto-shutdown should be available 

### Actual Behavior
The feature is not available

**Comment by retheshnair** [comment]
This is issues  to another [issues ](https://github.com/terraform-providers/terraform-provider-azurerm/issues/555)

**Comment by tombuildsstuff** [comment]
Hi @retheshnair 

Thanks for opening this issue :)

Just to let you know, this repository is for [the older Azure Service Management Provider](https://www.terraform.io/docs/providers/azure/index.html) ("the old portal") and not [the new Azure Resource Manager Provider](https://www.terraform.io/docs/providers/azurerm/index.html) ("the new portal") - which is what this feature request relates too.

There's [a feature request open to add support for DevTestLabs](https://github.com/terraform-providers/terraform-provider-azurerm/issues/132) on the AzureRM Provider, which includes support for schedules. Rather than having multiple issues tracking the same thing - I'm going to close this issue in favour of that one so that we can consolidate updates in one place.

Thanks!
